-- Current PostgreSQL schema for the experimental backend.
-- SQLite remains the default; this migration is used only when the PostgreSQL backend is explicitly selected.
CREATE EXTENSION IF NOT EXISTS unaccent;

DO $$
BEGIN
  CREATE COLLATION "COLLATION_UNICODE_3" (provider = icu, locale = 'und-u-ks-level3-kk-true', deterministic = false);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE COLLATION "NOCASE" (provider = icu, locale = 'und-u-ks-level2', deterministic = false);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE OR REPLACE FUNCTION "UDF_STRIP_ACCENTS"(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT unaccent(coalesce(value, '')) $$;

CREATE OR REPLACE FUNCTION udf_strip_accents(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT unaccent(coalesce(value, '')) $$;

CREATE TABLE "CLIENT_SETTINGS_GLOBAL" (
  "KEY" varchar NOT NULL,
  "VALUE" varchar NOT NULL,
  "ALLOW_UNAUTHORIZED" boolean NOT NULL DEFAULT false,
  CONSTRAINT "pk__client_settings_global" PRIMARY KEY ("KEY")
);

CREATE TABLE "COLLECTION" (
  "ID" varchar NOT NULL,
  "NAME" varchar NOT NULL,
  "ORDERED" boolean NOT NULL DEFAULT false,
  "SERIES_COUNT" integer NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pk__collection" PRIMARY KEY ("ID")
);

CREATE TABLE "HISTORICAL_EVENT" (
  "ID" varchar,
  "TYPE" varchar NOT NULL,
  "BOOK_ID" varchar,
  "SERIES_ID" varchar,
  "TIMESTAMP" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pk__historical_event" PRIMARY KEY ("ID")
);

CREATE TABLE "LIBRARY" (
  "ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "NAME" varchar NOT NULL,
  "ROOT" varchar NOT NULL,
  "IMPORT_COMICINFO_BOOK" boolean NOT NULL DEFAULT true,
  "IMPORT_COMICINFO_SERIES" boolean NOT NULL DEFAULT true,
  "IMPORT_COMICINFO_COLLECTION" boolean NOT NULL DEFAULT true,
  "IMPORT_EPUB_BOOK" boolean NOT NULL DEFAULT true,
  "IMPORT_EPUB_SERIES" boolean NOT NULL DEFAULT true,
  "SCAN_FORCE_MODIFIED_TIME" boolean NOT NULL DEFAULT false,
  "SCAN_STARTUP" boolean NOT NULL DEFAULT false,
  "IMPORT_LOCAL_ARTWORK" boolean NOT NULL DEFAULT true,
  "IMPORT_COMICINFO_READLIST" boolean NOT NULL DEFAULT true,
  "IMPORT_BARCODE_ISBN" boolean NOT NULL DEFAULT true,
  "CONVERT_TO_CBZ" boolean NOT NULL DEFAULT false,
  "REPAIR_EXTENSIONS" boolean NOT NULL DEFAULT false,
  "EMPTY_TRASH_AFTER_SCAN" boolean NOT NULL DEFAULT false,
  "IMPORT_MYLAR_SERIES" boolean NOT NULL DEFAULT true,
  "SERIES_COVER" varchar NOT NULL DEFAULT 'FIRST',
  "UNAVAILABLE_DATE" timestamp DEFAULT NULL,
  "HASH_FILES" boolean NOT NULL DEFAULT true,
  "HASH_PAGES" boolean NOT NULL DEFAULT false,
  "ANALYZE_DIMENSIONS" boolean NOT NULL DEFAULT true,
  "IMPORT_COMICINFO_SERIES_APPEND_VOLUME" boolean NOT NULL DEFAULT true,
  "ONESHOTS_DIRECTORY" varchar DEFAULT NULL,
  "SCAN_CBX" boolean NOT NULL DEFAULT true,
  "SCAN_PDF" boolean NOT NULL DEFAULT true,
  "SCAN_EPUB" boolean NOT NULL DEFAULT true,
  "SCAN_INTERVAL" varchar NOT NULL DEFAULT 'EVERY_6H',
  "HASH_KOREADER" boolean NOT NULL DEFAULT false,
  CONSTRAINT "pk__library" PRIMARY KEY ("ID")
);

CREATE TABLE "PAGE_HASH" (
  "HASH" varchar NOT NULL,
  "SIZE" bigint,
  "ACTION" varchar NOT NULL,
  "DELETE_COUNT" integer NOT NULL DEFAULT 0,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pk__page_hash" PRIMARY KEY ("HASH")
);

CREATE TABLE "PAGE_HASH_THUMBNAIL" (
  "HASH" varchar NOT NULL,
  "THUMBNAIL" bytea NOT NULL,
  CONSTRAINT "pk__page_hash_thumbnail" PRIMARY KEY ("HASH")
);

CREATE TABLE "READLIST" (
  "ID" varchar NOT NULL,
  "NAME" varchar NOT NULL,
  "BOOK_COUNT" integer NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "SUMMARY" varchar NOT NULL DEFAULT '',
  "ORDERED" boolean NOT NULL DEFAULT true,
  CONSTRAINT "pk__readlist" PRIMARY KEY ("ID")
);

CREATE TABLE "SERVER_SETTINGS" (
  "KEY" varchar NOT NULL,
  "VALUE" varchar,
  CONSTRAINT "pk__server_settings" PRIMARY KEY ("KEY")
);

CREATE TABLE "SIDECAR" (
  "URL" varchar NOT NULL,
  "PARENT_URL" varchar NOT NULL,
  "LAST_MODIFIED_TIME" timestamp NOT NULL,
  "LIBRARY_ID" varchar NOT NULL,
  CONSTRAINT "pk__sidecar" PRIMARY KEY ("URL")
);

CREATE TABLE "USER" (
  "ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "EMAIL" varchar NOT NULL,
  "PASSWORD" varchar NOT NULL,
  "SHARED_ALL_LIBRARIES" boolean NOT NULL DEFAULT true,
  "AGE_RESTRICTION" integer,
  "AGE_RESTRICTION_ALLOW_ONLY" boolean,
  CONSTRAINT "pk__user" PRIMARY KEY ("ID")
);

CREATE TABLE "ANNOUNCEMENTS_READ" (
  "USER_ID" varchar NOT NULL,
  "ANNOUNCEMENT_ID" varchar NOT NULL,
  CONSTRAINT "pk__announcements_read" PRIMARY KEY ("USER_ID", "ANNOUNCEMENT_ID")
);

CREATE TABLE "AUTHENTICATION_ACTIVITY" (
  "USER_ID" varchar DEFAULT NULL,
  "EMAIL" varchar DEFAULT NULL,
  "IP" varchar DEFAULT NULL,
  "USER_AGENT" varchar DEFAULT NULL,
  "SUCCESS" boolean NOT NULL,
  "ERROR" varchar DEFAULT NULL,
  "DATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "SOURCE" varchar DEFAULT NULL,
  "API_KEY_ID" varchar DEFAULT NULL,
  "API_KEY_COMMENT" varchar DEFAULT NULL
);

CREATE TABLE "CLIENT_SETTINGS_USER" (
  "USER_ID" varchar NOT NULL,
  "KEY" varchar NOT NULL,
  "VALUE" varchar NOT NULL,
  CONSTRAINT "pk__client_settings_user" PRIMARY KEY ("KEY", "USER_ID")
);

CREATE TABLE "HISTORICAL_EVENT_PROPERTIES" (
  "ID" varchar NOT NULL,
  "KEY" varchar NOT NULL,
  "VALUE" varchar NOT NULL,
  CONSTRAINT "pk__historical_event_properties" PRIMARY KEY ("ID", "KEY")
);

CREATE TABLE "LIBRARY_EXCLUSIONS" (
  "LIBRARY_ID" varchar NOT NULL,
  "EXCLUSION" varchar NOT NULL,
  CONSTRAINT "pk__library_exclusions" PRIMARY KEY ("LIBRARY_ID", "EXCLUSION")
);

CREATE TABLE "SERIES" (
  "ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "FILE_LAST_MODIFIED" timestamp NOT NULL,
  "NAME" varchar NOT NULL,
  "URL" varchar NOT NULL,
  "LIBRARY_ID" varchar NOT NULL,
  "BOOK_COUNT" integer NOT NULL DEFAULT 0,
  "DELETED_DATE" timestamp DEFAULT NULL,
  "oneshot" boolean NOT NULL DEFAULT false,
  CONSTRAINT "pk__series" PRIMARY KEY ("ID")
);

CREATE TABLE "SYNC_POINT" (
  "ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "USER_ID" varchar NOT NULL,
  "API_KEY_ID" varchar,
  CONSTRAINT "pk__sync_point" PRIMARY KEY ("ID")
);

CREATE TABLE "THUMBNAIL_COLLECTION" (
  "ID" varchar NOT NULL,
  "SELECTED" boolean NOT NULL DEFAULT false,
  "THUMBNAIL" bytea NOT NULL,
  "TYPE" varchar NOT NULL,
  "COLLECTION_ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "WIDTH" integer NOT NULL DEFAULT 0,
  "HEIGHT" integer NOT NULL DEFAULT 0,
  "MEDIA_TYPE" varchar NOT NULL DEFAULT '',
  "FILE_SIZE" bigint NOT NULL DEFAULT 0,
  CONSTRAINT "pk__thumbnail_collection" PRIMARY KEY ("ID")
);

CREATE TABLE "THUMBNAIL_READLIST" (
  "ID" varchar NOT NULL,
  "SELECTED" boolean NOT NULL DEFAULT false,
  "THUMBNAIL" bytea NOT NULL,
  "TYPE" varchar NOT NULL,
  "READLIST_ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "WIDTH" integer NOT NULL DEFAULT 0,
  "HEIGHT" integer NOT NULL DEFAULT 0,
  "MEDIA_TYPE" varchar NOT NULL DEFAULT '',
  "FILE_SIZE" bigint NOT NULL DEFAULT 0,
  CONSTRAINT "pk__thumbnail_readlist" PRIMARY KEY ("ID")
);

CREATE TABLE "USER_API_KEY" (
  "ID" varchar NOT NULL,
  "USER_ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "API_KEY" varchar NOT NULL,
  "COMMENT" varchar NOT NULL,
  CONSTRAINT "pk__user_api_key" PRIMARY KEY ("ID")
);

CREATE TABLE "USER_LIBRARY_SHARING" (
  "USER_ID" varchar NOT NULL,
  "LIBRARY_ID" varchar NOT NULL,
  CONSTRAINT "pk__user_library_sharing" PRIMARY KEY ("USER_ID", "LIBRARY_ID")
);

CREATE TABLE "USER_ROLE" (
  "USER_ID" varchar NOT NULL,
  "ROLE" varchar NOT NULL,
  CONSTRAINT "pk__user_role" PRIMARY KEY ("USER_ID", "ROLE")
);

CREATE TABLE "USER_SHARING" (
  "LABEL" varchar NOT NULL,
  "ALLOW" boolean NOT NULL,
  "USER_ID" varchar NOT NULL,
  CONSTRAINT "pk__user_sharing" PRIMARY KEY ("LABEL", "ALLOW", "USER_ID")
);

CREATE TABLE "BOOK" (
  "ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "FILE_LAST_MODIFIED" timestamp NOT NULL,
  "NAME" varchar NOT NULL,
  "URL" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL,
  "FILE_SIZE" bigint NOT NULL DEFAULT 0,
  "NUMBER" integer NOT NULL DEFAULT 0,
  "LIBRARY_ID" varchar NOT NULL,
  "FILE_HASH" varchar NOT NULL DEFAULT '',
  "DELETED_DATE" timestamp DEFAULT NULL,
  "oneshot" boolean NOT NULL DEFAULT false,
  "FILE_HASH_KOREADER" varchar NOT NULL DEFAULT '',
  CONSTRAINT "pk__book" PRIMARY KEY ("ID")
);

CREATE TABLE "BOOK_METADATA_AGGREGATION" (
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "RELEASE_DATE" date,
  "SUMMARY" varchar NOT NULL DEFAULT '',
  "SUMMARY_NUMBER" varchar NOT NULL DEFAULT '',
  "SERIES_ID" varchar NOT NULL,
  CONSTRAINT "pk__book_metadata_aggregation" PRIMARY KEY ("SERIES_ID")
);

CREATE TABLE "BOOK_METADATA_AGGREGATION_AUTHOR" (
  "NAME" varchar NOT NULL,
  "ROLE" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL
);

CREATE TABLE "BOOK_METADATA_AGGREGATION_TAG" (
  "TAG" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL
);

CREATE TABLE "COLLECTION_SERIES" (
  "COLLECTION_ID" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL,
  "NUMBER" integer NOT NULL,
  CONSTRAINT "pk__collection_series" PRIMARY KEY ("COLLECTION_ID", "SERIES_ID")
);

CREATE TABLE "READ_PROGRESS_SERIES" (
  "SERIES_ID" varchar NOT NULL,
  "USER_ID" varchar NOT NULL,
  "READ_COUNT" integer NOT NULL,
  "IN_PROGRESS_COUNT" integer NOT NULL,
  "MOST_RECENT_READ_DATE" timestamp,
  "LAST_MODIFIED_DATE" timestamp,
  CONSTRAINT "pk__read_progress_series" PRIMARY KEY ("SERIES_ID", "USER_ID")
);

CREATE TABLE "SERIES_METADATA" (
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "STATUS" varchar NOT NULL,
  "STATUS_LOCK" boolean NOT NULL DEFAULT false,
  "TITLE" varchar NOT NULL,
  "TITLE_LOCK" boolean NOT NULL DEFAULT false,
  "TITLE_SORT" varchar NOT NULL,
  "TITLE_SORT_LOCK" boolean NOT NULL DEFAULT false,
  "SERIES_ID" varchar NOT NULL,
  "PUBLISHER" varchar NOT NULL DEFAULT '',
  "PUBLISHER_LOCK" boolean NOT NULL DEFAULT false,
  "READING_DIRECTION" varchar,
  "READING_DIRECTION_LOCK" boolean NOT NULL DEFAULT false,
  "AGE_RATING" integer,
  "AGE_RATING_LOCK" boolean NOT NULL DEFAULT false,
  "SUMMARY" varchar NOT NULL DEFAULT '',
  "SUMMARY_LOCK" boolean NOT NULL DEFAULT false,
  "LANGUAGE" varchar NOT NULL DEFAULT '',
  "LANGUAGE_LOCK" boolean NOT NULL DEFAULT false,
  "GENRES_LOCK" boolean NOT NULL DEFAULT false,
  "TAGS_LOCK" boolean NOT NULL DEFAULT false,
  "TOTAL_BOOK_COUNT" integer,
  "TOTAL_BOOK_COUNT_LOCK" boolean NOT NULL DEFAULT false,
  "SHARING_LABELS_LOCK" boolean NOT NULL DEFAULT false,
  "LINKS_LOCK" boolean NOT NULL DEFAULT false,
  "ALTERNATE_TITLES_LOCK" boolean NOT NULL DEFAULT false,
  CONSTRAINT "pk__series_metadata" PRIMARY KEY ("SERIES_ID")
);

CREATE TABLE "SERIES_METADATA_ALTERNATE_TITLE" (
  "LABEL" varchar NOT NULL,
  "TITLE" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL
);

CREATE TABLE "SERIES_METADATA_GENRE" (
  "GENRE" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL
);

CREATE TABLE "SERIES_METADATA_LINK" (
  "LABEL" varchar NOT NULL,
  "URL" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL
);

CREATE TABLE "SERIES_METADATA_SHARING" (
  "LABEL" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL
);

CREATE TABLE "SERIES_METADATA_TAG" (
  "TAG" varchar NOT NULL,
  "SERIES_ID" varchar NOT NULL
);

CREATE TABLE "SYNC_POINT_BOOK" (
  "SYNC_POINT_ID" varchar NOT NULL,
  "BOOK_ID" varchar NOT NULL,
  "BOOK_CREATED_DATE" timestamp NOT NULL,
  "BOOK_LAST_MODIFIED_DATE" timestamp NOT NULL,
  "BOOK_FILE_LAST_MODIFIED" timestamp NOT NULL,
  "BOOK_FILE_SIZE" bigint NOT NULL,
  "BOOK_FILE_HASH" varchar NOT NULL,
  "BOOK_METADATA_LAST_MODIFIED_DATE" timestamp NOT NULL,
  "BOOK_READ_PROGRESS_LAST_MODIFIED_DATE" timestamp,
  "SYNCED" boolean NOT NULL DEFAULT false,
  "BOOK_THUMBNAIL_ID" varchar,
  CONSTRAINT "pk__sync_point_book" PRIMARY KEY ("SYNC_POINT_ID", "BOOK_ID")
);

CREATE TABLE "SYNC_POINT_BOOK_REMOVED_SYNCED" (
  "SYNC_POINT_ID" varchar NOT NULL,
  "BOOK_ID" varchar NOT NULL,
  CONSTRAINT "pk__sync_point_book_removed_synced" PRIMARY KEY ("SYNC_POINT_ID", "BOOK_ID")
);

CREATE TABLE "SYNC_POINT_READLIST" (
  "SYNC_POINT_ID" varchar NOT NULL,
  "READLIST_ID" varchar NOT NULL,
  "READLIST_NAME" varchar NOT NULL,
  "READLIST_CREATED_DATE" timestamp NOT NULL,
  "READLIST_LAST_MODIFIED_DATE" timestamp NOT NULL,
  "SYNCED" boolean NOT NULL DEFAULT false,
  CONSTRAINT "pk__sync_point_readlist" PRIMARY KEY ("SYNC_POINT_ID", "READLIST_ID")
);

CREATE TABLE "SYNC_POINT_READLIST_BOOK" (
  "SYNC_POINT_ID" varchar NOT NULL,
  "READLIST_ID" varchar NOT NULL,
  "BOOK_ID" varchar NOT NULL,
  CONSTRAINT "pk__sync_point_readlist_book" PRIMARY KEY ("SYNC_POINT_ID", "READLIST_ID", "BOOK_ID")
);

CREATE TABLE "SYNC_POINT_READLIST_REMOVED_SYNCED" (
  "SYNC_POINT_ID" varchar NOT NULL,
  "READLIST_ID" varchar NOT NULL,
  CONSTRAINT "pk__sync_point_readlist_removed_synced" PRIMARY KEY ("SYNC_POINT_ID", "READLIST_ID")
);

CREATE TABLE "THUMBNAIL_SERIES" (
  "ID" varchar NOT NULL,
  "URL" varchar DEFAULT NULL,
  "SELECTED" boolean NOT NULL DEFAULT false,
  "THUMBNAIL" bytea DEFAULT NULL,
  "TYPE" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "SERIES_ID" varchar NOT NULL,
  "WIDTH" integer NOT NULL DEFAULT 0,
  "HEIGHT" integer NOT NULL DEFAULT 0,
  "MEDIA_TYPE" varchar NOT NULL DEFAULT '',
  "FILE_SIZE" bigint NOT NULL DEFAULT 0,
  CONSTRAINT "pk__thumbnail_series" PRIMARY KEY ("ID")
);

CREATE TABLE "BOOK_METADATA" (
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "NUMBER" varchar NOT NULL,
  "NUMBER_LOCK" boolean NOT NULL DEFAULT false,
  "NUMBER_SORT" double precision NOT NULL,
  "NUMBER_SORT_LOCK" boolean NOT NULL DEFAULT false,
  "RELEASE_DATE" date,
  "RELEASE_DATE_LOCK" boolean NOT NULL DEFAULT false,
  "SUMMARY" varchar NOT NULL DEFAULT '',
  "SUMMARY_LOCK" boolean NOT NULL DEFAULT false,
  "TITLE" varchar NOT NULL,
  "TITLE_LOCK" boolean NOT NULL DEFAULT false,
  "AUTHORS_LOCK" boolean NOT NULL DEFAULT false,
  "TAGS_LOCK" boolean NOT NULL DEFAULT false,
  "BOOK_ID" varchar NOT NULL,
  "ISBN" varchar NOT NULL DEFAULT '',
  "ISBN_LOCK" boolean NOT NULL DEFAULT false,
  "LINKS_LOCK" boolean NOT NULL DEFAULT false,
  CONSTRAINT "pk__book_metadata" PRIMARY KEY ("BOOK_ID")
);

CREATE TABLE "BOOK_METADATA_AUTHOR" (
  "NAME" varchar NOT NULL,
  "ROLE" varchar NOT NULL,
  "BOOK_ID" varchar NOT NULL
);

CREATE TABLE "BOOK_METADATA_LINK" (
  "LABEL" varchar NOT NULL,
  "URL" varchar NOT NULL,
  "BOOK_ID" varchar NOT NULL
);

CREATE TABLE "BOOK_METADATA_TAG" (
  "TAG" varchar NOT NULL,
  "BOOK_ID" varchar NOT NULL
);

CREATE TABLE "MEDIA" (
  "MEDIA_TYPE" varchar,
  "STATUS" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "COMMENT" varchar,
  "BOOK_ID" varchar NOT NULL,
  "PAGE_COUNT" integer NOT NULL DEFAULT 0,
  "EXTENSION_CLASS" varchar,
  "_UNUSED" varchar,
  "EXTENSION_VALUE_BLOB" bytea,
  "EPUB_DIVINA_COMPATIBLE" boolean NOT NULL DEFAULT false,
  "EPUB_IS_KEPUB" boolean NOT NULL DEFAULT false,
  CONSTRAINT "pk__media" PRIMARY KEY ("BOOK_ID")
);

CREATE TABLE "MEDIA_FILE" (
  "FILE_NAME" varchar NOT NULL,
  "BOOK_ID" varchar NOT NULL,
  "MEDIA_TYPE" varchar,
  "SUB_TYPE" varchar,
  "FILE_SIZE" bigint
);

CREATE TABLE "MEDIA_PAGE" (
  "FILE_NAME" varchar NOT NULL,
  "MEDIA_TYPE" varchar NOT NULL,
  "NUMBER" integer NOT NULL,
  "BOOK_ID" varchar NOT NULL,
  "width" integer,
  "height" integer,
  "FILE_HASH" varchar NOT NULL DEFAULT '',
  "FILE_SIZE" bigint,
  CONSTRAINT "pk__media_page" PRIMARY KEY ("BOOK_ID", "NUMBER")
);

CREATE TABLE "READLIST_BOOK" (
  "READLIST_ID" varchar NOT NULL,
  "BOOK_ID" varchar NOT NULL,
  "NUMBER" integer NOT NULL,
  CONSTRAINT "pk__readlist_book" PRIMARY KEY ("READLIST_ID", "BOOK_ID")
);

CREATE TABLE "READ_PROGRESS" (
  "BOOK_ID" varchar NOT NULL,
  "USER_ID" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PAGE" integer NOT NULL,
  "COMPLETED" boolean NOT NULL,
  "READ_DATE" timestamp DEFAULT CURRENT_TIMESTAMP,
  "device_id" varchar DEFAULT '',
  "device_name" varchar DEFAULT '',
  "locator" bytea,
  CONSTRAINT "pk__read_progress" PRIMARY KEY ("BOOK_ID", "USER_ID")
);

CREATE TABLE "THUMBNAIL_BOOK" (
  "ID" varchar NOT NULL,
  "THUMBNAIL" bytea,
  "URL" varchar,
  "SELECTED" boolean NOT NULL DEFAULT false,
  "TYPE" varchar NOT NULL,
  "CREATED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LAST_MODIFIED_DATE" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "BOOK_ID" varchar NOT NULL,
  "WIDTH" integer NOT NULL DEFAULT 0,
  "HEIGHT" integer NOT NULL DEFAULT 0,
  "MEDIA_TYPE" varchar NOT NULL DEFAULT '',
  "FILE_SIZE" bigint NOT NULL DEFAULT 0,
  "GENERATION_PROFILE" varchar DEFAULT NULL,
  CONSTRAINT "pk__thumbnail_book" PRIMARY KEY ("ID")
);

ALTER TABLE "ANNOUNCEMENTS_READ" ADD CONSTRAINT "fk__announcements_read__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "AUTHENTICATION_ACTIVITY" ADD CONSTRAINT "fk__authentication_activity__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "CLIENT_SETTINGS_USER" ADD CONSTRAINT "fk__client_settings_user__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "HISTORICAL_EVENT_PROPERTIES" ADD CONSTRAINT "fk__historical_event_properties__0" FOREIGN KEY ("ID") REFERENCES "HISTORICAL_EVENT" ("ID");
ALTER TABLE "LIBRARY_EXCLUSIONS" ADD CONSTRAINT "fk__library_exclusions__0" FOREIGN KEY ("LIBRARY_ID") REFERENCES "LIBRARY" ("ID");
ALTER TABLE "SERIES" ADD CONSTRAINT "fk__series__0" FOREIGN KEY ("LIBRARY_ID") REFERENCES "LIBRARY" ("ID");
ALTER TABLE "SYNC_POINT" ADD CONSTRAINT "fk__sync_point__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "THUMBNAIL_COLLECTION" ADD CONSTRAINT "fk__thumbnail_collection__0" FOREIGN KEY ("COLLECTION_ID") REFERENCES "COLLECTION" ("ID");
ALTER TABLE "THUMBNAIL_READLIST" ADD CONSTRAINT "fk__thumbnail_readlist__0" FOREIGN KEY ("READLIST_ID") REFERENCES "READLIST" ("ID");
ALTER TABLE "USER_API_KEY" ADD CONSTRAINT "fk__user_api_key__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "USER_LIBRARY_SHARING" ADD CONSTRAINT "fk__user_library_sharing__0" FOREIGN KEY ("LIBRARY_ID") REFERENCES "LIBRARY" ("ID");
ALTER TABLE "USER_LIBRARY_SHARING" ADD CONSTRAINT "fk__user_library_sharing__1" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "USER_ROLE" ADD CONSTRAINT "fk__user_role__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "USER_SHARING" ADD CONSTRAINT "fk__user_sharing__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "BOOK" ADD CONSTRAINT "fk__book__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "BOOK" ADD CONSTRAINT "fk__book__1" FOREIGN KEY ("LIBRARY_ID") REFERENCES "LIBRARY" ("ID");
ALTER TABLE "BOOK_METADATA_AGGREGATION" ADD CONSTRAINT "fk__book_metadata_aggregation__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "BOOK_METADATA_AGGREGATION_AUTHOR" ADD CONSTRAINT "fk__book_metadata_aggregation_author__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "BOOK_METADATA_AGGREGATION_TAG" ADD CONSTRAINT "fk__book_metadata_aggregation_tag__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "COLLECTION_SERIES" ADD CONSTRAINT "fk__collection_series__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "COLLECTION_SERIES" ADD CONSTRAINT "fk__collection_series__1" FOREIGN KEY ("COLLECTION_ID") REFERENCES "COLLECTION" ("ID");
ALTER TABLE "READ_PROGRESS_SERIES" ADD CONSTRAINT "fk__read_progress_series__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "READ_PROGRESS_SERIES" ADD CONSTRAINT "fk__read_progress_series__1" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "SERIES_METADATA" ADD CONSTRAINT "fk__series_metadata__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "SERIES_METADATA_ALTERNATE_TITLE" ADD CONSTRAINT "fk__series_metadata_alternate_title__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "SERIES_METADATA_GENRE" ADD CONSTRAINT "fk__series_metadata_genre__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "SERIES_METADATA_LINK" ADD CONSTRAINT "fk__series_metadata_link__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "SERIES_METADATA_SHARING" ADD CONSTRAINT "fk__series_metadata_sharing__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "SERIES_METADATA_TAG" ADD CONSTRAINT "fk__series_metadata_tag__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "SYNC_POINT_BOOK" ADD CONSTRAINT "fk__sync_point_book__0" FOREIGN KEY ("SYNC_POINT_ID") REFERENCES "SYNC_POINT" ("ID");
ALTER TABLE "SYNC_POINT_BOOK_REMOVED_SYNCED" ADD CONSTRAINT "fk__sync_point_book_removed_synced__0" FOREIGN KEY ("SYNC_POINT_ID") REFERENCES "SYNC_POINT" ("ID");
ALTER TABLE "SYNC_POINT_READLIST" ADD CONSTRAINT "fk__sync_point_readlist__0" FOREIGN KEY ("SYNC_POINT_ID") REFERENCES "SYNC_POINT" ("ID");
ALTER TABLE "SYNC_POINT_READLIST_BOOK" ADD CONSTRAINT "fk__sync_point_readlist_book__0" FOREIGN KEY ("SYNC_POINT_ID") REFERENCES "SYNC_POINT" ("ID");
ALTER TABLE "SYNC_POINT_READLIST_REMOVED_SYNCED" ADD CONSTRAINT "fk__sync_point_readlist_removed_synced__0" FOREIGN KEY ("SYNC_POINT_ID") REFERENCES "SYNC_POINT" ("ID");
ALTER TABLE "THUMBNAIL_SERIES" ADD CONSTRAINT "fk__thumbnail_series__0" FOREIGN KEY ("SERIES_ID") REFERENCES "SERIES" ("ID");
ALTER TABLE "BOOK_METADATA" ADD CONSTRAINT "fk__book_metadata__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "BOOK_METADATA_AUTHOR" ADD CONSTRAINT "fk__book_metadata_author__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "BOOK_METADATA_LINK" ADD CONSTRAINT "fk__book_metadata_link__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "BOOK_METADATA_TAG" ADD CONSTRAINT "fk__book_metadata_tag__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "MEDIA" ADD CONSTRAINT "fk__media__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "MEDIA_FILE" ADD CONSTRAINT "fk__media_file__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "MEDIA_PAGE" ADD CONSTRAINT "fk__media_page__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "READLIST_BOOK" ADD CONSTRAINT "fk__readlist_book__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "READLIST_BOOK" ADD CONSTRAINT "fk__readlist_book__1" FOREIGN KEY ("READLIST_ID") REFERENCES "READLIST" ("ID");
ALTER TABLE "READ_PROGRESS" ADD CONSTRAINT "fk__read_progress__0" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "READ_PROGRESS" ADD CONSTRAINT "fk__read_progress__1" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");
ALTER TABLE "THUMBNAIL_BOOK" ADD CONSTRAINT "fk__thumbnail_book__0" FOREIGN KEY ("BOOK_ID") REFERENCES "BOOK" ("ID");

CREATE UNIQUE INDEX "idx__user__unique__email" ON "USER" ("EMAIL");
CREATE INDEX "idx__authentication_activity__user_id" ON "AUTHENTICATION_ACTIVITY" ("USER_ID");
CREATE INDEX "idx__library_exclusions__library_id" ON "LIBRARY_EXCLUSIONS" ("LIBRARY_ID");
CREATE INDEX "idx__series__created_date" ON "SERIES" ("CREATED_DATE");
CREATE INDEX "idx__series__last_modified_date" ON "SERIES" ("LAST_MODIFIED_DATE");
CREATE INDEX "idx__series__library_id" ON "SERIES" ("LIBRARY_ID");
CREATE INDEX "idx__sync_point__user_id" ON "SYNC_POINT" ("USER_ID");
CREATE INDEX "idx__thumbnail_collection__collection_id" ON "THUMBNAIL_COLLECTION" ("COLLECTION_ID");
CREATE INDEX "idx__thumbnail_readlist__readlist_id" ON "THUMBNAIL_READLIST" ("READLIST_ID");
CREATE INDEX "idx__user_api_key__user_id" ON "USER_API_KEY" ("USER_ID");
CREATE UNIQUE INDEX "idx__user_api_key__unique__api_key" ON "USER_API_KEY" ("API_KEY");
CREATE INDEX "idx__book__created_date" ON "BOOK" ("CREATED_DATE");
CREATE INDEX "idx__book__library_id" ON "BOOK" ("LIBRARY_ID");
CREATE INDEX "idx__book__series_id" ON "BOOK" ("SERIES_ID");
CREATE INDEX "idx__book_metadata_aggregation_author__series_id" ON "BOOK_METADATA_AGGREGATION_AUTHOR" ("SERIES_ID");
CREATE INDEX "idx__book_metadata_aggregation_tag__series_id" ON "BOOK_METADATA_AGGREGATION_TAG" ("SERIES_ID");
CREATE INDEX "idx__series_metadata__title" ON "SERIES_METADATA" ("TITLE");
CREATE INDEX "idx__series_metadata_alternate_title__series_id" ON "SERIES_METADATA_ALTERNATE_TITLE" ("SERIES_ID");
CREATE INDEX "idx__series_metadata_genre__series_id" ON "SERIES_METADATA_GENRE" ("SERIES_ID");
CREATE INDEX "idx__series_metadata_link__series_id" ON "SERIES_METADATA_LINK" ("SERIES_ID");
CREATE INDEX "idx__series_metadata_sharing__series_id" ON "SERIES_METADATA_SHARING" ("SERIES_ID");
CREATE INDEX "idx__series_metadata_tag__series_id" ON "SERIES_METADATA_TAG" ("SERIES_ID");
CREATE INDEX "idx__sync_point_book__sync_point_id" ON "SYNC_POINT_BOOK" ("SYNC_POINT_ID");
CREATE INDEX "idx__sync_point_book_removed_status__sync_point_id" ON "SYNC_POINT_BOOK_REMOVED_SYNCED" ("SYNC_POINT_ID");
CREATE INDEX "idx__sync_point_readlist__sync_point_id" ON "SYNC_POINT_READLIST" ("SYNC_POINT_ID");
CREATE INDEX "idx__sync_point_readlist_book__sync_point_id_readlist_id" ON "SYNC_POINT_READLIST_BOOK" ("SYNC_POINT_ID", "READLIST_ID");
CREATE INDEX "idx__thumbnail_series__series_id" ON "THUMBNAIL_SERIES" ("SERIES_ID");
CREATE INDEX "idx__book_metadata__release_date" ON "BOOK_METADATA" ("RELEASE_DATE");
CREATE INDEX "idx__book_metadata__number_sort" ON "BOOK_METADATA" ("NUMBER_SORT");
CREATE INDEX "idx__book_metadata_author__book_id" ON "BOOK_METADATA_AUTHOR" ("BOOK_ID");
CREATE INDEX "idx__book_metadata_link__book_id" ON "BOOK_METADATA_LINK" ("BOOK_ID");
CREATE INDEX "idx__book_metadata_tag__book_id" ON "BOOK_METADATA_TAG" ("BOOK_ID");
CREATE INDEX "idx__media__status" ON "MEDIA" ("STATUS");
CREATE INDEX "idx__media_file__book_id" ON "MEDIA_FILE" ("BOOK_ID");
CREATE INDEX "idx__read_progress__last_modified_date" ON "READ_PROGRESS" ("LAST_MODIFIED_DATE");
CREATE INDEX "idx__thumbnail_book__file_size" ON "THUMBNAIL_BOOK" ("FILE_SIZE");
CREATE INDEX "idx__thumbnail_book__height" ON "THUMBNAIL_BOOK" ("HEIGHT");
CREATE INDEX "idx__thumbnail_book__width" ON "THUMBNAIL_BOOK" ("WIDTH");
CREATE INDEX "idx__thumbnail_book__book_id" ON "THUMBNAIL_BOOK" ("BOOK_ID");
